### ISSUE TITLE
Installation steps?

### ISSUE THREAD

**Issue by krdyke** [OpenGeoportal/ogpHarvester#77]
Hi,

I'd like to give the harvester a spin to see if it'll fit our needs, but would rather not spend a bunch of time tracking down the various bits I need to configure on my own via trial and error. Could I get a set of what needs to be addressed? For example it looks like Posgres is needed, as well as Solr. Should the LocalSolr url be the same one used by our OGP instance, or should it have its own Solr?

Any help is much appreciated.

**Comment by juanluisrp** [comment]
LocalSolr is the URL where the harvested data will be stored. Postgres is used basically to store configuration and the scheduled harvests. Postgres connection is configured in [jdbc.properties](https://github.com/OpenGeoportal/ogpHarvester/blob/master/web/src/main/resources/spring/jdbc.properties). The Solr instance URL is configured in [localSolr.properties](https://github.com/OpenGeoportal/ogpHarvester/blob/master/web/src/main/resources/spring/localSolr.properties)

**Comment by krdyke** [comment]
Thanks, that got me in the right direction.
